name: Build

on:
  push:
    branches:
      - "**"
    paths:
      - '.github/workflows/**'
      - 'src/**'

permissions:
  contents: write

env:
  PLUGIN_NAME: obsidian-sample-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup Environment
        run: |
          corepack enable
          yarn set version stable

      - name: Build
        run: |
          yarn
          yarn lint
          yarn build
          mv dist/main.js main.js

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}
          path: |
            main.js
            manifest.json